### ISSUE TITLE
57分から59分のときに表示されなくなる

### ISSUE THREAD

**Issue by DaichiSontyou** [503-Lab/U-LRT-Timetable#10]
23時57分など日時を更新した際に表示しないようにする処理が
現在時刻+3分足した時間が
現在時刻と等しくない場合に表示しないようになっているため
20時57分
↓+3分
21時00分
20時と21時は等しくないため表示されない
など

**Comment by malken21** [comment]
https://github.com/503-Lab/U-LRT-Timetable/pull/12
修正しました。
